### ISSUE TITLE
MATVT Support

### ISSUE THREAD

**Issue by AndrewChqng** [mt8695/android_device_amazon_sheldon#1]
Hi would it be possible to implement this patch? The apps super useful but the alternative adb control is very buggy and the gesture api works much better
https://github.com/virresh/matvt/issues/28#issuecomment-1020814825
Many Thanks!

**Comment by diego-cr** [comment]
It's already merged on LOS

https://github.com/LineageOS/android_frameworks_base/commit/e1e3273b10c53a618483c8f96075effe51a6b033
https://github.com/LineageOS/android_frameworks_base/commit/8078813107b6699ab6976b6e2f3c57f158d2147c

Thanks

**Comment by AndrewChqng** [comment]
Oh, oops, not sure why matvt doesn't work for me except on the Google tv launcher, it's very annoying but hopefully it's just me and other people don't have problems with it
