### ISSUE TITLE
Bluetooth mouse 5.0 “Couldn’t pair”

### ISSUE THREAD

**Issue by papypaprika** [mt8695/android_device_amazon_sheldon#3]
Hello,
I have the following message when I try to pair my mouse Razer Deathadder V2 Pro via Bluetooth 5.0:
“Couldn’t pair”.
Any ideas why this is happening?

EDIT:
Updated the firmware of the mouse and it now works!

**Comment by R0rt1z2** [comment]
> Hello, I have the following message when I try to pair my mouse Razer Deathadder V2 Pro via Bluetooth 5.0: “Couldn’t pair”. Any ideas why this is happening?

Without logs I can't really help you. Try to grab some while pairing the device.

**Comment by papypaprika** [comment]
Updating mouse firmware solves the issue.
